### ISSUE TITLE
Request shizuku support

### ISSUE THREAD

**Issue by songsammy** [flxapps/DetoxDroid#10]
Shizuku is an app that emulates adb on an android device. It will enable wireless debug on the device and connect it.
With shizuku, we don't need the computer to do the setup. All we need is a few clicks.
This may be useful for someone who don't have access to a computer.

**Comment by flxapps** [comment]
I don't quite understand that app. You still need a computer to set up Shizuku though, is that correct? 

I will look at how easily that can be implemented and if I can properly test it, but at this point, I see a very limited use.

**Comment by songsammy** [comment]
For the question of whether a computer is needed, yes for android 10 and below, no for android 11 and higher.
And probably you are right. Maybe it is not as useful as i had thought.
