### ISSUE TITLE
Malware Detected

### ISSUE THREAD

**Issue by kyorakudev** [flxapps/DetoxDroid#110]
I run an antivirus scan in my phone and detected malware. then I check the APK file on virustotal 
result :
![image](https://github.com/flxapps/DetoxDroid/assets/49984708/6e0035ac-c078-4793-8a4f-5bc33b883180)
is it a false positive or not?

**Comment by flxapps** [comment]
This is a false positive, probably because the app is very tightly intertwined with Android features (like using an accessibility service under the hood, being able to deactivate other apps, etc.).
