### ISSUE TITLE
Deactivated app not reactivating

### ISSUE THREAD

**Issue by structure37** [flxapps/DetoxDroid#112]
Hi, an app I configured for deactivation was deactivated yesterday after using it for the allotted time, but now it's not reactivating! I tried removing it from the deactivation list, turning off Disable Apps, stopping DetoxDroid, and using `adb shell pm enable com.grindrapp.android`, but none worked. Any advice on how I can get the app to be enabled again? I don't have an app backup so deleting it and reinstalling isn't an option for me.

**Comment by flxapps** [comment]
Hi, thanks for your bug report. This should be fixed with [PR#113](https://github.com/flxapps/DetoxDroid/pull/113). I will issue a new release in a moment.

**Comment by flxapps** [comment]
v2.0.6 build here: https://github.com/flxapps/DetoxDroid/releases/tag/v2.0.6

Please just update your app and report back to me if it works.

**Comment by flxapps** [comment]
Your adb shell command should work, too, though.

**Comment by flxapps** [comment]
@structure37 Has the issue been fixed?

**Comment by structure37** [comment]
I had just woken up and was in a hurry and didn't realize I typed out the whole adb command. That's embarrassing! Yes, I updated DetoxDroid and it resolved. Thank you so much!
