### ISSUE TITLE
Scheduled Disable Apps Option

### ISSUE THREAD

**Issue by M00NJ** [flxapps/DetoxDroid#119]
At the moment you can only set an allowed amount of screen time, after which an app is blocked / deactivated. It would be nice if a schedule option, like for the grayscale was available here as well. For example, if I'm in Bed watching YouTube while I should be sleeping, it would be helpful if I could block YouTube between 11pm and 8am.

**Comment by einkleinerwolf** [comment]
Yes please. I also would find it very helpful to have this function

**Comment by M00NJ** [comment]
I think this project is dead :(
