### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by arnoldsecret** [flxapps/DetoxDroid#12]
Currently on my Android 6.0.1 phone, it shows a Parse error whilst attempting to install the apk.

**Comment by flxapps** [comment]
I cannot reproduce this issue in an Android 6.0 emulator. Is this issue new in relation with v1.1.0 or do you have also problems installing [older versions](https://github.com/flxapps/DetoxDroid/releases)?

Can you try the [this build (zipped apk first)](https://github.com/flxapps/DetoxDroid/files/5980473/app-release.zip)? It is the current version, but I have deactivated proguard which might cause the issue.

**Comment by arnoldsecret** [comment]
Turns out the issue persists even if using an older version and the zipped apk that you just sent.

**Comment by flxapps** [comment]
Have you disabled the "Allow installation from unknown resources" setting by any chance?

**Comment by arnoldsecret** [comment]
I have it turned on
