### ISSUE TITLE
granting app elevated privileges on Pc doesnt work?

### ISSUE THREAD

**Issue by benytzlich** [flxapps/DetoxDroid#13]
Tried to install via .bat and via alternative method:
receive message in cmd.exe after executing (platform-tools\adb.exe install -r app-release.apk
platform-tools\adb.exe shell pm grant com.flx_apps.digitaldetox android.permission.WRITE_SECURE_SETTINGS) :
- adb error : device not authorized
- adb vendor not set

Win 8.1
Android 8.0

Am i missing something?

cheers, 
Beny

![grafik](https://user-images.githubusercontent.com/73239828/107943928-ab4db300-6f8d-11eb-9adf-ad8566b8f5d2.png)
![grafik](https://user-images.githubusercontent.com/73239828/107943973-be608300-6f8d-11eb-9dfb-4853bbdcb4da.png)

**Comment by flxapps** [comment]
Have your tried this? https://stackoverflow.com/a/25546300/1684030

**Comment by benytzlich** [comment]
I already reauthorized adb device. didnt work.
2nd time after your hint: it WORKED. Thanks ! I am curious
