### ISSUE TITLE
Get's Stuck in a Color On/Off loop when "Gesture Up" to switch apps

### ISSUE THREAD

**Issue by TheTurtleBear** [flxapps/DetoxDroid#18]
I'm using GrapheneOS on Pixel 4xl and this may be related to the GrapheneOS or the Launcher, so this may not be a good app for me.
I set my calendar app (for example) as an exception to the Automatic Grayscale rule.
I open the app and it is colored like it should be. I gesture up from the bottom and it starts flickering color on and off and gets stuck in a loop until I break it by forcing the phone to restart. Depending on the app, or maybe how I gesture, I'm able to get back to the home screen. It seems that it is conflicting with the gesture navigation when navigating from a colored app.

I love the idea of the app though.

**Comment by flxapps** [comment]
Might be related to #20
