### ISSUE TITLE
Change rermission to draw over other apps?

### ISSUE THREAD

**Issue by 2br-2b** [flxapps/DetoxDroid#2]
Thanks for making this amazing app!

In order to not require the WRITE_SECURE_SETTINGS permission (and thus requiring command line installation), is something like what [Red Moon](https://github.com/LibreShift/red-moon) does possible?

Basically, Red Moon uses the permission to draw over other apps to apply a red filter to the screen. Could something like that be done in black and white?

This would take a lot of refactoring, though.

**Comment by flxapps** [comment]
Hi, thank you very much for your suggestion. I have initially actually developed this app, but I figured I might as well go open source with it and see if anybody else finds it helpful, and it is amazing to see this in fact happening.

In regards to your suggestion: This is what I actually tried in the beginning. However, I had to find out that this is not possible. Yes, it is possible to blend an overlay color with the screen content. But in doing so, you can only make the screen more reddish, or more blueish, or greenish, or whatever. You can also make the screen darker or lighter. What you unfortuenately cannot achieve with this method is true grayscale.

**Comment by 2br-2b** [comment]
Hi!

I'm glad to see that you tried this, but sad to see that it doesn't work.

Thanks for open-sourcing this project! It is a really cool project. I've been looking for something like this since removing Google's digital wellbeing, but this is the first FOSS app I've found with this functionality.

This is really useful, but I wish there was an easier way to install it. Good idea making all of the individual install scripts for the different platforms, though!
