### ISSUE TITLE
Request: Detect App In Work Profile

### ISSUE THREAD

**Issue by ghost** [flxapps/DetoxDroid#23]
Is that clear your app detoxdroid can exclude some app from grayscale but detox droid cannot Exclude app from work profile 

I don't want clone this app to work profile though :-(

**Comment by flxapps** [comment]
Hello, have you tried adding an app named "System" or "Android System" or something like that to your exclusion list?

**Comment by flxapps** [comment]
Alternatively, you could always use the "quick pause" feature

**Comment by NSTAdventure** [comment]
> Alternatively, you could always use the "quick pause" feature

man i am lazy to open those app often :( 

just pls add some way to detect app in work profile :((((((
