### ISSUE TITLE
android.permission.ACCESS_NOTIFICATION_POLICY is not a changeable permission type

### ISSUE THREAD

**Issue by KarlR83** [flxapps/DetoxDroid#28]
I'm trying to give DetoxDroid the necessary permissions as described in the [installation instructions](https://github.com/flxapps/DetoxDroid#installation)

I'm using _install_windows.bat_ script and get the following error:

> C:\Users\peterpan\Downloads\DetoxDroid-master\install>install_windows.bat
> Downloading and unzipping Android Platform Tools. Please wait...
> Starting ADB
> If your device asks you to allow USB Debugging, press "Accept".
> Granting Permissions
> 
> Exception occurred while executing 'grant':
> java.lang.SecurityException: Permission android.permission.ACCESS_NOTIFICATION_POLICY requested by com.flx_apps.digitaldetox is not a changeable permission type
>         at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:451)
>         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1457)
>         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1410)
>         at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2287)
>         at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:249)
>         at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
>         at android.os.ShellCommand.exec(ShellCommand.java:44)
>         at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21702)
>         at android.os.Binder.shellCommand(Binder.java:929)
>         at android.os.Binder.onTransact(Binder.java:813)
>         at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4621)
>         at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4319)
>         at android.os.Binder.execTransactInternal(Binder.java:1159)
>         at android.os.Binder.execTransact(Binder.java:1123)
> Starting App
>   bash arg: -p
>   bash arg: com.flx_apps.digitaldetox
>   bash arg: 1
> args: [-p, com.flx_apps.digitaldetox, 1]
>  arg: "-p"
>  arg: "com.flx_apps.digitaldetox"
>  arg: "1"
> data="com.flx_apps.digitaldetox"
> Events injected: 1
> ## Network stats: elapsed time=14ms (0ms mobile, 0ms wifi, 14ms not connected)
> Done.

Comparing what the batch script does with what the [manual installation instructions](https://github.com/flxapps/DetoxDroid/wiki/Manual-Installation) say, I can see that the manual instructions only ask to grant _android.permission.WRITE_SECURE_SETTINGS_ but not _android.permission.ACCESS_NOTIFICATION_POLICY_

Why is the batch script doing both? Is this a bug in the script or are the manual instructions incomplete?
Can I ignore _android.permission.ACCESS_NOTIFICATION_POLICY_ error or are they really necessary for DetoxDroid to work?

**Comment by flxapps** [comment]
Hi @KarlR83. The permission is used to automatically (de-)activate the "zen mode" (aka "do not disturb" mode). The error is odd, I did not run into it myself. The permission can be granted via the app though, so it is not necessary to grant it with the installation script.
