### ISSUE TITLE
[Improvement] Grayscale exceptions option to ignore certain apps

### ISSUE THREAD

**Issue by lkotlarenko** [flxapps/DetoxDroid#3]
Hi there, I'm loving the app and noticed something that would improve the automatic grayscale, here is an explanation:
When selected to gray any app that contains text input and the keyboard is required if the keyboard app is on color mode, while you are typing the app that is supposed to be on gray scale will be colorful until the keyboard is open. Well than if you put the keyboard app on gray scale too than the inverse case occurs.
This same type of case can happen if the System UI is selected to keep colors and while on an app that needs to be gray you try to change the volume. 

Well than, here is my solution: If an list of "ignored apps" is added than this type of misbehavior can be solved, the apps on this list would always use the same color scheme as the last used app.
Sorry if I misspelled something or acted rude, english isn't my mother tongue.
Many thanks, great app ;)

**Comment by flxapps** [comment]
Hello, thanks for your suggestion, this is a good idea and I will try to implement it into the Exceptions list in the future.

**Comment by flxapps** [comment]
Okay, so after looking into this again: Your issue is that when you are opening your keyboard (which is added to the exceptions) in a grayscaled app, you only expect your keyboard to be colored, but not the background?

**Comment by lkotlarenko** [comment]
> Okay, so after looking into this again: Your issue is that when you are opening your keyboard (which is added to the exceptions) in a grayscaled app, you only expect your keyboard to be colored, but not the background?

Thanks for looking at it :)
Not exactly, I just wanted that when I opened a app that is supposed to be in grayscale that it remained in that way even if I open the keyboard or tried to change the volume. Here is a more exemplified explanation: I have WhatsApp placed in grayscale, than I need to type, if the keyboard app is set to color than when I am typing the whole WhatsApp is put on color, I can resolve putting the keyboard on grayscale to (my keyboard is only black and white anyway) but than if I do that and try to use an app in color (bromite for example) when the keyboard pops up the app is put on grayscale. The same to system ui (when trying to pull down notifications or changing the volume).
If was possible to put those apps on an "follow the last app state" than when I opened whatsapp (gray) the keyboard would be gray too, but on apps put on exemption like bromite or newpipe (color), the keyboard would be on color mode too.
Pretty confusing lol (sorry for the bad explanation)
I hope you understand, thank you again 👍

**Comment by lkotlarenko** [comment]
Here, I recorded a simple video to demonstrate:
[https://youtu.be/l0e-nMBOfC8](url)
Hope it helps you understand better

**Comment by flxapps** [comment]
Mhm, I do have them sometimes, too, but I cannot really reproduce these glitches on my device. I think this is mostly an Android-related issue. What seems to happen is that the OS sometimes does not fire an event (TYPE_WINDOW_STATE_CHANGED) when it is supposed to (i.e. when you close the notification shade). That being said, changing the volume should actually be ignored in terms of grayscale/non-grayscale.

The only thing I think I could do is to completely ignore the notification shade (and other non-fullscreen windows like the volume dialog, keyboards, etc.). But that would mean that you could not have colored notifications when you open them from a grayscaled app.

**Comment by lkotlarenko** [comment]
> Mhm, I do have them sometimes, too, but I cannot really reproduce these glitches on my device. I think this is mostly an Android-related issue. What seems to happen is that the OS sometimes does not fire an event (TYPE_WINDOW_STATE_CHANGED) when it is supposed to (i.e. when you close the notification shade). That being said, changing the volume should actually be ignored in terms of grayscale/non-grayscale.
> 
> The only thing I think I could do is to completely ignore the notification shade (and other non-fullscreen windows like the volume dialog, keyboards, etc.). But that would mean that you could not have colored notifications when you open them from a grayscaled app.

I do not mind that, if its possible I would love so.
Many thanks, with that I could leave the grayscale option on always on.
