### ISSUE TITLE
Feature request: timer and schedule

### ISSUE THREAD

**Issue by foldfree** [flxapps/DetoxDroid#35]
Would be great to have a timer to limit usage of specified apps after a certain time.

Also a schedule option for the grayscale, to automatically trigger grayscale at night for example.

Another minor enhancement possible is to have the app follows the light/dark theme system of android 10+

**Comment by theuser18** [comment]
I would like to second this request. Both limiting apps to "x" number of minutes or hours each day and only within the window of, let's say 10:00 and 7:00 pm would be great!
