### ISSUE TITLE
Coming back to life after pause not working

### ISSUE THREAD

**Issue by flxapps** [flxapps/DetoxDroid#39]
Submitter: Marco
Oneplus 7 OOS11 stock rom
Enabled pause (1 min) in quicksettings for the black and white mode but after 1 min the colors don't change. 
after I open detox Droid it works again

**Comment by jnnkB** [comment]
I have this issue too. If you need any more information for debugging I'm happy to help.

**Comment by jnnkB** [comment]
Duplicate of #38
