### ISSUE TITLE
Can't install on linux

### ISSUE THREAD

**Issue by turtaf** [flxapps/DetoxDroid#4]
Using popOS 20.04, everything updated

When following the "easy" instructions, I get the following (either with sudo or without it)

`gatto@pop-os:~/Downloads$ sudo bash install_linux.sh 
Installing Detox Droid on your device
Performing Push Install
adb: error: failed to get feature set: no devices/emulators found
Granting Permissions
adb: no devices/emulators found
Starting App
adb: no devices/emulators found
Done.
`

So I tried the manual installation, to get a little deeper insight...

`gatto@pop-os:~/Downloads$ platform-tools/adb install -r app-release.apk
adb server version (39) doesn't match this client (41); killing...`

`* daemon started successfully
Performing Push Install
adb: error: failed to get feature set: no devices/emulators found
`

I tried some googling, but couldn't solve it...
Before I mess something up, is there any hint?

**Comment by dominikstrb** [comment]
Does `adb devices` show any devices?

**Comment by turtaf** [comment]
> Does `adb devices` show any devices?

Nope...

`gatto@pop-os:~/Downloads$ adb devices
List of devices attached`
`
gatto@pop-os:~/Downloads$
`

**Comment by flxapps** [comment]
Hi! I can confirm that I have also set my phone to "Charge only" when connecting it to my laptop. Please make also sure to select "Charge only" under Settings → Developer options → Networking → Select USB configuration. 

Besides, you can find a couple of other things (like disabling and re-enabling USB debugging) you can try here: https://stackoverflow.com/questions/21170392/android-device-does-not-show-up-in-adb-list

**Comment by flxapps** [comment]
What's also weird is that the message

> adb server version (39) doesn't match this client (41); killing...

suggests that you also have another instance of an older version of adb running in the background. Do you use Android Studio or something that could explain this? You could try to forcefully kill adb in a process manager and try again.

**Comment by turtaf** [comment]
Absolutely my bad.
Entered developer mode, but forgot to enter usb debugging mode.

Now installed like a charm.

Very sorry for wasting your time.
Cheers and thanks,

Emanuele
