### ISSUE TITLE
Allow different grayscale color

### ISSUE THREAD

**Issue by sapristi** [flxapps/DetoxDroid#44]
Hello, thanks for this awesome app ! I just installed it for grayscale, and I like that. 

An idea that I just had (while thinking of how this differs from my e-reader), is to allow to have a "colored" grayscale, e.g. with a warmer tone. So this is just my 2 cents about a possible extra feature :)

(although maybe this would defeat the point of grayscale to some extent ? I don't really know)

**Comment by strider72** [comment]
Turn on the Android "Night Light" feature to make it a warmer tone. Works well along with Detox's grayscale
