### ISSUE TITLE
Cannot disable grayscale

### ISSUE THREAD

**Issue by sandboiii** [flxapps/DetoxDroid#5]
Hello, I tried this app, at first it seemed to be working fine. Later I tried to disable grayscale and it didn't do anything. My phone now is in full grayscale mode. Grayscale disabled in Detox app, but display is still grayscale. All exception settings are ignored. I don't know how to fix this. My phone is OnePlus 8 IN2010 with lastest firmware Android 11.

**Comment by sandboiii** [comment]
Oh, somehow I managed to disable this. I noticed there are native grayscale settings in this phone. But I'm not sure how it works. Maybe it conflicts with the app's grayscale settings and I somehow messed it up

**Comment by flxapps** [comment]
Hello. Beginning with Android 10 I think there is a native grayscale setting embedded into the "bedtime mode". It does not allow for excluding certain apps though as far as I know.

Besides, you can turn on/off grayscale under Developer options → Simulate color space → Monochromacy/Off. This is actually what the app turns on/off, too.

**Comment by sandboiii** [comment]
I tried to reproduce this issue and turns out this has nothing to do with Android's grayscale. The app itself is just being unintuitive to use which lead me to think there was a glitch. There is the automatic grayscale option which can be checked to enable grayscale. However unchecking it doesn't disable grayscale. To disable grayscale I need to press floating button. And this is what made me think the app is broken.

**Comment by flxapps** [comment]
I am closing this for now but will keep your comments concerning the UI in mind. I did not invest too much time into it yet. The floating button is thought to be a "master switch", while the checkboxes are meant to be "fine-tuning options". But I think you are right, it is not too intuitive.
