### ISSUE TITLE
One issue with detox droid

### ISSUE THREAD

**Issue by 5paceghost** [flxapps/DetoxDroid#51]
Hey there,
happy new year! 
This App is awesome and a great help for my day to day life.
One thing that often happens though is that apps which are excluded from the black and white mode snap from color mode to black and white after some minutes of use. I experience this with games for instance. This can be fixed by leaving the app and returning. But it would be great if this issue would be fixed.
I will send you a donation in the next minutes. 

Take care and Stay healthy!

**Comment by flxapps** [comment]
Hi,
could you say how to exactly reproduce this issue? Which games? Under which circumstances?
Regards,
Felix

**Comment by 5paceghost** [comment]
Hey there,

 

please excuse my delayed answer.

Concerning the issue that DetoxDroid 'switches' into grayscale mode while using apps that are on the exception list:

I observed the issue and I noticed that not only games are affected but most of the apps that are on the exception list.

 

These are a few of the apps that sometimes switch into grayscale mode and can be brought back into color mode by

opening the recent apps list and returning into the app:

 

https://play.google.com/store/apps/details?id=net.wearefamily.readinglamp

https://play.google.com/store/apps/details?id=com.netflix.NGP.CardBlast

https://play.google.com/store/apps/details?id=com.netflix.NGP.AsphaltXtreme

https://play.google.com/store/apps/details?id=com.calengoo.android

https://play.google.com/store/apps/details?id=com.fddb

 

I am using a OnePlus 8 (Modell IN2013) with Android 11. My phone is rooted with magisk.

 

Kind regards,

Felix

 
 

Gesendet: Dienstag, 18. Januar 2022 um 13:04 Uhr
Von: "flxapps" ***@***.***>
An: "flxapps/DetoxDroid" ***@***.***>
Cc: "5paceghost" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [flxapps/DetoxDroid] One issue with detox droid (Issue #51)


 

Hi,
could you say how to exactly reproduce this issue? Which games? Under which circumstances?
Regards,
Felix

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 5paceghost** [comment]
Dear Felix, thank you for the latest update of detox Droid. I noticed one major problem though: The grayscale mode exceptions only shows detox Droid as the only user app. Could you please fix this? Because this also has the effect that all apps now are in grayscale which were excepted. Big thanks in advance! Take care, Felix Am 18.01.22, 13:04 schrieb flxapps ***@***.***>:

   
  Hi, could you say how to exactly reproduce this issue? Which games? Under which circumstances? Regards, Felix
