### ISSUE TITLE
App switcher (square button) crashes

### ISSUE THREAD

**Issue by strider72** [flxapps/DetoxDroid#53]
Using DetoxDroid seems to crash the Android app switcher (the square button). Something to do with switching between color and grayscale while switching apps. The square button simply stops working at all until I reboot.

Maybe add a small delay before switching. Half a second after I switch apps before the color changes?

**Comment by flxapps** [comment]
Hello, does this only happen with the latest version (v1.2.0) or already before? Seems to me to be device- and/or OS-related. Can you provide these information?

**Comment by strider72** [comment]
Apparently it's a problem with AOSP 12, dating back to beta but not fixed.
