### ISSUE TITLE
Install instructions UX

### ISSUE THREAD

**Issue by vimalamp** [flxapps/DetoxDroid#57]
The command on the install instructions in the app do not include `adb shell dpm set-device-owner com.flx_apps.digitaldetox/.DetoxDroidDeviceAdminReceiver`. It would be nice to be able to make the command text that is there now selectable as well.

The button in the app to learn more points to the main website instead of the actual instructions.

**Comment by flxapps** [comment]
I'm not sure I understand. This permission is only needed for the "deactivate apps" feature and the mentioned command is in fact shown when you try to use that specific feature.

**Comment by vimalamp** [comment]
it is a step in your install instructions. Maybe clarify it's not needed?
