### ISSUE TITLE
[Feature Request] Suspend Or disable apps via ADB

### ISSUE THREAD

**Issue by ghost** [flxapps/DetoxDroid#58]
problem:
detoxdroid have ability to hide app using devices owner mode but this one isn't practical since you need to logout from all account first only for just enable devices owner mode
![Screenshot_2022-02-07-04-54-40-93](https://user-images.githubusercontent.com/50813528/152703087-6f34b48c-7a98-47b8-8b38-bc9b039572ad.jpg)

solution:
Add ADB over TCP support so user can using this feature with ADB
if possible please use suspend instead of disable
but you need to add popup msg to confirm or security measures
(because suspended app still can be unsuspended easily by launch greyed out icon / launcher)

**Comment by NSTAdventure** [comment]
> This feature is pretty experimental and I only tested it on the emulator. So what you are saying is that if there are multiple profiles used on the device, granting the app the "device owner" permission is not as trivial as running the mentioned ADB command?

I don't know sir 🙏

i think it should work 
but for detoxdroid user who want to use those kind feature on multiply user (work profile etc etc)
then delegate devices owner mode / root is right choice for you

disclaimer:
my idea it's optional there is no coercion here
🙏😄
