### ISSUE TITLE
possible to setup only with root access?

### ISSUE THREAD

**Issue by Emporea** [flxapps/DetoxDroid#6]
If one doesnt have a pc but root access, is there a possibility to setup the app? I dont know via terminal maybe?

**Comment by lkotlarenko** [comment]
> If one doesnt have a pc but root access, is there a possibility to setup the app? I dont know via terminal maybe?

Yeah, download this: https://github.com/MuntashirAkon/AppManager
(It's a really good app manager)
Install it and change the mode of operation to root on the app manager settings. Then find detox droid on the app manager list, go to user permissions and check android.permission.WRITE_SECURE_SETTINGS to on.
![IMG-20210117-WA0000](https://user-images.githubusercontent.com/56134431/104852035-21c69a80-5894-11eb-8403-bd12145c9ce6.jpg)
![IMG-20210117-WA0001](https://user-images.githubusercontent.com/56134431/104852038-225f3100-5894-11eb-9962-a614c9aeee0b.jpg)
![IMG-20210117-WA0002](https://user-images.githubusercontent.com/56134431/104852037-21c69a80-5894-11eb-9416-41272a639849.jpg)
![IMG-20210117-WA0003](https://user-images.githubusercontent.com/56134431/104852033-20956d80-5894-11eb-8124-b7ed811e9110.jpg)

**Comment by voodoovikingz** [comment]
Very helpfull. But do any know how to femove F@$£b00k app manager. Remove all of that nasty stuf from my device ?

**Comment by lkotlarenko** [comment]
> Very helpfull. But do any know how to femove F@$£b00k app manager. Remove all of that nasty stuf from my device ?!

Yup, click on the APP you want to remove and select uninstall (I would recommend to backup the .apk first).
Remember to reboot the device after removing the apps.

![IMG-20210119-WA0000](https://user-images.githubusercontent.com/56134431/105105693-af52e780-5a58-11eb-8b34-e45b180bb8c9.jpg)
![IMG-20210119-WA0001](https://user-images.githubusercontent.com/56134431/105105697-b11cab00-5a58-11eb-9060-ba96539b0cf8.jpg)
![IMG-20210119-WA0002](https://user-images.githubusercontent.com/56134431/105105699-b11cab00-5a58-11eb-9a49-c380dafd9709.jpg)
![IMG-20210119-WA0003](https://user-images.githubusercontent.com/56134431/105105695-b0841480-5a58-11eb-9a14-01e06e5c7fbb.jpg)
![IMG-20210119-WA0004](https://user-images.githubusercontent.com/56134431/105105700-b1b54180-5a58-11eb-9466-7746108cdcd4.jpg)

**Comment by voodoovikingz** [comment]
Thanks alot. But I this app of Hu@/ei does'nt give the same options in the Appmanager. ![Screenshot_20210120_093054_io.github.muntashirakon.AppManager.jpg](https://user-images.githubusercontent.com/76601648/105148419-a4549180-5b02-11eb-9cfb-bba510c4f958.jpg)![Screenshot_20210120_093111.jpg](https://user-images.githubusercontent.com/76601648/105148435-a7e81880-5b02-11eb-8114-0f5f4404e525.jpg)

**Comment by voodoovikingz** [comment]
Is it becoursr this kind of app needs to be rooted

**Comment by voodoovikingz** [comment]
![Screenshot_20210120_093557_io.github.muntashirakon.AppManager.jpg](https://user-images.githubusercontent.com/76601648/105148673-f1d0fe80-5b02-11eb-8239-62cc93844b71.jpg)

**Comment by voodoovikingz** [comment]
Same menu dropdown for G*****. Excuse me if I'm totally a Noob.

**Comment by voodoovikingz** [comment]
![Screenshot_20210120_094408.jpg](https://user-images.githubusercontent.com/76601648/105149656-111c5b80-5b04-11eb-9d2d-e738d7d4f8fa.jpg)

**Comment by voodoovikingz** [comment]
Only backup and restore I find in settimgs

**Comment by voodoovikingz** [comment]
![Screenshot_20210120_095202.jpg](https://user-images.githubusercontent.com/76601648/105150546-2fcf2200-5b05-11eb-96ed-e0b285cc769f.jpg)

**Comment by voodoovikingz** [comment]
does it make any sense at all. Remove and uinstall this kind of app's. Then to reinstall a Factory version which in my logic sense just appear and isn't removed

**Comment by flxapps** [comment]
I just released a new version ([v1.0.2](https://github.com/flxapps/DetoxDroid/releases/tag/v1.0.2)) that should support this feature. I cannot really test it as I do not have a rooted device currently.

Please give some feedback if possible.

**Comment by Emporea** [comment]
Yeah it's working. Greyscale is on.But the overall handling of settings and activating is a bit unclear and seems buggy to me.

**Comment by voodoovikingz** [comment]
I will definetily give you feedback. When my salary is up for buying a backup phone and an extra Sim.Just in case I brick this one attempting to root. Thank you very muc for devolping this app and sharing

**Comment by voodoovikingz** [comment]
https://shop.fairphone.com/en/fairphone-3-plus

**Comment by lkotlarenko** [comment]
> I will definetily give you feedback. When my salary is up for buying a backup phone and an extra Sim.Just in case I brick this one attempting to root. Thank you very muc for devolping this app and sharing

Remember to always have a backup of your device, using a custom recovery is possible to backup so that if something goes wrong you can restore without any problems, I use rooted phones since 2013 and only have had 2 problems that needed a complete restore. You just have to be careful and not modify system apps that you are unsure of.

**Comment by Emporea** [comment]
@flxapps 

Honestly, i like this app so much. So simple and yet useful. 
I mean, I dont have any Google Services on my Phone anyway, nor any social media stuff (excuses: reddit, github.. ? :D), but this completes my plan to give me back control over my phone. I feel like colorful things are almost like sugar. I use my phone almost only for usefull stuff, since I downloaded this app.

Thank you.

**Comment by voodoovikingz** [comment]
> @flxapps 
> 
> Honestly, i like this app so much. So simple and yet useful. 
> I mean, I dont have any Google Services on my Phone anyway, nor any social media stuff (excuses: reddit, github.. ? :D), but this completes my plan to give me back control over my phone. I feel like colorful things are almost like sugar. I use my phone almost only for usefull stuff, since I downloaded this app.
> 
> Thank you.
> 

My purpose is similar. having a "clean" phone from companyspies. Seling my Datasoul for their service maked me feeling insecure. but i'm still a slave of their coomercial world. I need a bank account by the Danish law to get salery. We have a forced socailsystem in denmark. all my mails from the danish state and communes go though an app. even though that the sold our infrastructure to private companies make me anxious. I do not trust this private companies. They just want to make money.

I can not run around in the city with two phones. One which are unrooted and Tracked. And one phone unrooted with freedom apps which is not tracked. The tracked phone will even send out ELS signal ifnits turned out. I can put in a bag isolated from radiowaves and make it safe. But then not easily and fast switching my persona use.
