### ISSUE TITLE
Can't add Camera or Gallery on Exceptions for the Automatic Grayscale

### ISSUE THREAD

**Issue by HenriJD** [flxapps/DetoxDroid#61]
I'm using the latest Version 1.2.1 on a Pixel 4 with the latest GrapheneOS (Android 12)

Here is a screen recording of the app list.

https://gfycat.com/queasybitesizedfirefly

Why isn't the camera and galary showing up in the list?

**Comment by AnonymousSeal** [comment]
Yeah same problem on my fairphone 4: exclusion list is pretty incomplete and it looks like i can only exclude stock android apps. Can't exclude my simple mobile apps.
