### ISSUE TITLE
Quick settings tile disabled, shows unavailable

### ISSUE THREAD

**Issue by vimalamp** [flxapps/DetoxDroid#67]
After upgrading to anything above version 1.1.0 (currently on 1.2.1) the quick settings tile to pause the grayscale option is grayed out

**Comment by quwepiro** [comment]
https://github.com/flxapps/DetoxDroid/blob/8381bcff1a5cb171565e75fb6914261d5dcf2150/app/src/main/AndroidManifest.xml#L67

The QuickTilesService has exported = false, I think this is the reason.
@flxapps  I could create a pull request for this, if needed.

**Comment by KamilBaczkowski** [comment]
Is this getting worked on?

**Comment by fridewald** [comment]
I downgraded the app because neither this setting nor the long press home button worked for me on Android 11
