### ISSUE TITLE
Problem installing on Linux (Raspbian 10 buster, armv7l)

### ISSUE THREAD

**Issue by dontlookmysnake** [flxapps/DetoxDroid#7]
I already have DetoxDroid installed on my smartphone (Android 7), but have to complete installation from a PC. I already unzipped the required file and changed directory. When I run `bash install_linux.sh` (with sudo or without it) I get

`Installing Detox Droid on your device`
`install_linux.sh: line 15: platform-tools/adb: cannot execute binary file: Exec format error`
`Granting Permissions`
`install_linux.sh: line 18: platform-tools/adb: cannot execute binary file: Exec format error`
`Starting App`
`install_linux.sh: line 21: platform-tools/adb: cannot execute binary file: Exec format error`
`Done.`

I don't know what should I do. USB debugging is enabled and I have no problem with adb.

**Comment by flxapps** [comment]
It seems like the later versions of adb (the script downloads the latest) are not working on 32bit processors anymore. You could try to follow the manual installation steps, but using an older version of adb that supports your processor.

https://github.com/flxapps/DetoxDroid/wiki/Manual-Installation
https://dl.google.com/android/repository/platform-tools_r23.0.1-linux.zip

**Comment by dontlookmysnake** [comment]
It works, thank you :)
Great app!
