### ISSUE TITLE
Confusing scheduling rules

### ISSUE THREAD

**Issue by FlingCarnationProposal** [flxapps/DetoxDroid#75]
I'm trying to create a schedule to activate all day on weekdays and only activate during nighttime to morning on the next day on weekends, but no matter how I try to configure the rules, I couldn't get it to work beyond activating it on weekdays. It seems to apply a confusing blend of activate/deactivate rules, at least that's what I can tell. 

Please make the rules a bit more clear or redo the scheduling logic so that it makes sense. Preferably, the schedule could be set to activating or deactivating, and from there, I can configure at what time that applies.

**Comment by flxapps** [comment]
Scheduling is more fine-grained now and should suit your needs (feedback welcome).
