### ISSUE TITLE
Request feature: Schedules and "force brick'

### ISSUE THREAD

**Issue by songsammy** [flxapps/DetoxDroid#8]
Here's what i am thinking about: 
In certain jobs phones are necessary. So I want grayscale disabled during work hours.
I don't have a good will, so i need to turn it on for hours.
On Friday night i want a treat, so every Friday it is colourd

In my country, the university entrance examination is important, and before that i want to stop phone usage.I want more aggressive features to brick my phone.
I'm not sure if i made it clear, but you can try GeoGebra's Exam mode, in which you can't disable untill time up.
Or just like a kitchen safe keeping cookie out of reach .

**Comment by voodoovikingz** [comment]
Exstremly Thank You😁

Sendt fra ProtonMail-mobil

-------- Originalbesked --------
Til 6. feb. 2021 11.14, Sam skrev:

**Comment by songsammy** [comment]
I really appreciate this app.
While using it for some few minutes, i am thinking about some more features.I will open a new issue

**Comment by voodoovikingz** [comment]
Thank you so much. I donated even that I haven't really figured out everything. But there's hope where there is will. 

I tried to set up through the link on PC. I use Fedora. Now everything is frizen and runs very slow. Maybe its not Detox. Just becourse I'm to greedy learning new free open source programs on my HDD😆

**Comment by songsammy** [comment]
Draw over other apps.
I am sorry i didn't make it clear the first time.
Here's what i mean. At 11:00pm , when i turn on the screen, the app draws a hardly transparent layer with words on it saying. "Its time to go to bed"
Or after using the phone for an hour, the app draws the layer saying, Its time for a rest.

**Comment by songsammy** [comment]
And the lock screen means,
https://www.geogebra.org/exam
You pin the screen.
The user sets a time duration,  the app check whether the aeroplane mode is on and blue tooth off,and pin the screen,show the timer.
Now the phone is (nearly) useless. 
Just like you have put the phone into a kitchen safe.
![Screenshot_2021-02-10-11-28-25-237_org mozilla firefox](https://user-images.githubusercontent.com/30046778/107460524-3ba58580-6b93-11eb-8ffc-d462a3a647d6.jpg)

**Comment by voodoovikingz** [comment]
Thank you for guiding my fried braincells. I will now put my head into the microwave while being in dreamland🤯
