### ISSUE TITLE
Feature request: short form video scrolling

### ISSUE THREAD

**Issue by GlitchCat** [flxapps/DetoxDroid#82]
Detect and prevent endlessly watching short form videos (such as on services like TikTok, YouTube shorts and Instagram reels), much like how 'break infinite scrolling' detects doom scrolling.

'break infinite scrolling' currently does not detect scrolling through (and optionally watching) short form videos. I propose that either:
- the 'break infinite scrolling' feature also detects such type of scrolling. (Maybe make it an option which type of scrolling the user wants to detect: doom scrolling, short form video scrolling or both)
- there comes a second type of detection specifically for endlessly watching and scrolling through short form videos

**Comment by flxapps** [comment]
should work properly with v2.0.0 release (please give feedback, only tested on instagram)
