### ISSUE TITLE
Feature Request: Schedule Always On Display

### ISSUE THREAD

**Issue by jollySleeper** [flxapps/DetoxDroid#93]
We already have an Option to Schedule the GrayScale Mode. Can we also have an option to Schedule Always On Display as the permission are already gained for Enabling GrayScale Mode.

Thank You

**Comment by flxapps** [comment]
Hi, what do you mean by "Schedule Always On Display", can you elaborate?

**Comment by jollySleeper** [comment]
Hi @flxapps Sorry for the late reply.
Just like GrayScale can be toggled On/Off, we can schedule this too.

So, same way can me Schedule Triggering "Always On Display"

**Comment by flxapps** [comment]
Can you elaborate how this would relate to the purpose of the app (i.e. spending less time using the smartphone)?

**Comment by jollySleeper** [comment]
If the user has enabled Always on Display, the notifications can make it to AlwaysOnDisplay which can be distracting and a trigger for distraction.
I know I can always Turn on DoNotDisturb but this make me forget about my mobile at night knowing that AOD is off I won't start looking for my mobile in dark.
