### ISSUE TITLE
Application requires permissions granted

### ISSUE THREAD

**Issue by Stomatic** [flxapps/DetoxDroid#94]
Hi, I have successfully installed the granted permissions via the procedure on the PC, despite this I cannot use the application.
Every time I try to start the application by clicking on the "Start DetoxDroid" button, I get a banner telling me that the application does not have permissions (I mean the ones to be given by following the procedure on the computer), despite the fact that the application has the necessary permissions (the installation procedure was successful), in fact by activating the "Automatic Grayscale" mode the phone turns black and white.
Also if I activate this mode the "App Exceptions" feature does not work, in fact the phone remains black and white even in the selected apps (however if I put DetoxDroid in the apps to exclude, the phone does not become black and white).
My last problem is about the sudden deactivation of the application, if I activate the application via the "Start DetoxDroid" button after a few minutes (about 1-2) it deactivates itself.
I use GrapheneOS as my operating system, I am using app version 2.0.2, and I gave the application all permissions, the installation procedure was successful, and I even tried to do it all over again but nothing changed

**Comment by ParetoOptimalDev** [comment]
> I use GrapheneOS as my operating system, I am using app version 2.0.2, and I gave the application all permissions, the installation procedure was successful, and I even tried to do it all over again but nothing changed

Just as a data point, I also use GrapheneOS. Things initially worked for me, but as I [commented](https://github.com/flxapps/DetoxDroid/issues/92#issuecomment-1841298938) it then stopped working.

Perhaps the optimization that GrapheneOS does could ahve something to do with it.

The next thing I will try is looking for any compatibility settings, the following come to mind:

https://grapheneos.org/usage#sandboxed-google-play-configuration

The other is whether some of the advanced security features conflict with the permission we gave detoxdroid over adb like:

https://grapheneos.org/faq#hardware-identifiers
